### ISSUE TITLE
Test the project with new branches

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/o3de-demo-project#11]
Ubuntu 22.04 with Humble and:
- [O3DE](https://github.com/o3de/o3de) - stabilization/2210
- [ROS2 Gem](https://github.com/RobotecAI/o3de-ros2-gem) - main
- [Loft Scene Sample](https://github.com/aws-lumberyard/loft-arch-vis-sample) - main

If it works, update commit hashes or tags ("tested with ..") in the description

**Comment by spham-amzn** [comment]
We should use either https://github.com/aws-lumberyard-dev/o3de/tree/roscon_2022 or https://github.com/o3de/o3de

**Comment by adamdbrw** [comment]
This was tested with our docker tests (with O3DE development branch)
