### ISSUE TITLE
Docker readme indicates navstack is launchable from the simulation image

### ISSUE THREAD

**Issue by smurly** [RobotecAI/o3de-demo-project#24]
the current readme.md indicates that you build the robot_vacuum sample which contains both the simulation and the navigationstack and that you launch each by changing the target from `LaunchSimulation.bash` to `LaunchNavStack.bash`
it then indicates you can (optionally) build the navigation stack as a second image. the navigation stack image is actually a required step since the first image fails with an error if you `LaunchNavStack.bash` with it

Repro
1. `sudo docker build -t o3de_robot_vacuum_simulation:latest .`
2. `sudo docker run --rm --network="bridge" --gpus all -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix -it o3de_robot_vacuum_simulation:latest /data/workspace/LaunchSimulation.bash`
3. open a second terminal
4. `sudo docker run --rm --network="bridge" --gpus all -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix -it o3de_robot_vacuum_simulation:latest /data/workspace/LaunchNavStack.bash`

`[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'rviz2' not found, searching: ['/opt/ros/humble']"`

5. `sudo docker build --build-arg IMAGE_TYPE=navstack -t o3de_robot_vacuum_navstack:latest .`
this is listed as "You can also create a separate docker image" but this is actually the required process you must then create a separate docker image.
6. `sudo docker run --rm --network="bridge" --gpus all -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix -it o3de_robot_vacuum_navstack:latest /data/workspace/LaunchNavStack.bash`
Now this executes the rviz and interacts with the simulation.

please update the docker readme.md two paragraphs to indicate the first image builds the simulation and the second image is required and builds the navigation stack so basically update this section of text:
```
This will create a docker image named 'o3de_robot_vacuum_simulation' with the tag 'latest' that contains both the simulation launcher and the navigation stack. It will also contain helper scripts that will launch either the simulation (LaunchSimulation.bash) or the Rviz2 (LaunchNavStack.bash).

You can also create a separate docker image that only contains the navigation stack and Rviz2 by supplying the argument IMAGE_TYPE and setting it to 'navstack':```

**Comment by spham-amzn** [comment]
Actually I think it will be better to have the simulation also contain support for the navstack as well (and match the readme). This is to not force the user to create a separate docker image if they are not interested in running that particular scenario (cross docker image communication).

**Comment by smurly** [comment]
single image contains simulation and navigation now
